### ISSUE TITLE
[CERTIFICADO] <Digite seu nome completo> 

### ISSUE THREAD

**Issue by edivanalves** [codaqui/institucional#168]
### Código de Conduta

- [X] Eu já li o [Código de Conduta](https://www.codaqui.dev/conduta/) e concordo com ele.

### Comentários

em quanto tempo posso receber o certificado ?

**Comment by endersonmenezes** [comment]
Vou verificar o seu certificado, um momento.

**Comment by endersonmenezes** [comment]
Oi @edivanalves você precisa completar todos os exercicios propostos aqui: https://github.com/codaqui/certificado-python-edivanalves

O certificado será emitido após a correção.
