### ISSUE TITLE
[Marketing] Visita as Universidades

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#213]
Doc Privado: https://docs.google.com/document/d/1LF1Wv6mv499p4FrvRhOc92wWnce_Whw8hwPzPa6cXI0/edit

**Comment by endersonmenezes** [comment]
Estamos sem nenhum contato com a Uningá e a Software By Maringá.

**Comment by endersonmenezes** [comment]
@anadevti esse mesmo contato seu dos e-mails consegue dar uma ajuda pra gente visitar os cursos de ti e divulgar a comunidade e o evento?

**Comment by endersonmenezes** [comment]
Em andamento.

**Comment by anadevti** [comment]
@endersonmenezes perdão, não vi que me mencionou. ainda precisa de apoio em algo?

**Comment by endersonmenezes** [comment]
Tá tranquilo @anadevti.

Docs atualizado.

**Comment by endersonmenezes** [comment]
Oficio COPEJEM.
