### ISSUE TITLE
[Pré-Evento] Local para Pré Evento

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#214]
Objetivo: ~Realizar contato com o SESC e verificar disponibilidade do espaço de anfiteatro e laboratórios para o dia anterior ao evento~

Edit: Procurar um novo local com capacidade para ~100 pessoas.

**Comment by endersonmenezes** [comment]
Enviado o e-mail para o SESC e sem resposta.

**Comment by anadevti** [comment]
Enviado email novamente.

**Comment by anadevti** [comment]
com o sesc infelizmente não vai rolar como segue na resposta do e-mail abaixo:



![Image](https://github.com/codaqui/institucional/assets/111382055/b64f1029-e473-4b96-8e2b-e8a4902529e7)

**Comment by anadevti** [comment]
![Image](https://github.com/codaqui/institucional/assets/111382055/223ccead-82ed-4500-875c-476eaceb4e16)

Enviado novo email, mas agora para a faculdade FCV.

**Comment by endersonmenezes** [comment]
O @ByIvo citou durante a reunião depois da resposta da FCV de tentar um contato com a EVOA e com o SEBRAE.

**Comment by anadevti** [comment]
![image](https://github.com/codaqui/institucional/assets/111382055/0373e0cb-3306-4e5c-8fa6-712a5f3d7fe5)
Resposta da UNIFCV!

**Comment by anadevti** [comment]
@endersonmenezes me auxiliando na task.

**Comment by endersonmenezes** [comment]
Fizemos contato com reitor da UNICV, estamos conversando. E agora o Antonio demonstrou interesse em ser na UniCesumar.

Beneficios UNICV - Localização.
Beneficios UniCesumar - Estacionamento.

Ambos os locais possuem infra que necessitamos.

**Comment by endersonmenezes** [comment]
O único pedido da UniCesumar foi de ter 30 vagas divulgadas antes dos Workshops. Está em análise.

**Comment by endersonmenezes** [comment]
@anadevti sinaliza o Jorge que devido à demora nos contatos a UniCesumar entrou em contato com a gente para negociar.

**Comment by anadevti** [comment]
@endersonmenezes repassei para ele.

**Comment by anadevti** [comment]
Subimos uma votação para  a comunidade escolher o melhor local.

**Comment by anadevti** [comment]
Foi decidido que iremos ter o pré evento na Unicesumar!
