### ISSUE TITLE
[Empresa] AmbevTech

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#215]
- Apresentação do Evento (e-mail coorporativo, cc ivo@devpr.org, cc, comunidade@devpr.org)
  - Auto apresentar, apresentar o Ivo como Coordenador de Relações Institucionais.
- Apresentação a Associação, explicar a mescla DevPR com a Codaqui. (CNPJ).
- Abertura para Proposta.

Proposta de e-mail:

Assunto: Apoie o DevParaná Conference 2024

Meu nome é [Seu Nome] e escrevo em nome do DevParaná buscando apoio da **EMPRESA** para a realização da DevParaná Conference 2024, que acontecerá no Teatro Calil Haddad na cidade de Maringá/PR no dia 28 de Julho.

Nessa edição chegamos com uma proposta diferente das edições passadas, pois estamos buscando apoio da comunidade como um todo para realização de um evento gratuito para cerca de 800 pessoas. Isso será feito através de patrocínios e apoios individuais onde cada modelo de apoio receberá benefícios exclusivos (como reservar local no teatro e alguns brindes da edição).

Você pode apoiar nosso evento através da compra de no mínimo **X** cotas para seus colaboradores, onde cada cota custa R$ 100,00 e garante os benefícios para uma pessoa.

Fazendo isso, você garantirá:

- Sua marca apoiando o DevParaná e disponível no [site](https://devpr.org);
- A marca da empresa apareça como apoiadora nos nossos materiais de divulgação do evento;
- Oferecer a reserva e garantia de lugar no teatro para seus colaboradores (de acordo com a quantidade de cotas apoiadas);
- Promover o desenvolvimento dos seus colaboradores;
- Fortalecer o engajamento de seus colaboradores junto à comunidade regional;
- Garantir brindes exclusivos do evento aos participantes;
- **Fortalecer a nossa comunidade, garantindo que continuaremos organizando eventos por mais um ano.**

Agora o DevParaná está junto da [Codaqui](https://www.codaqui.dev/#objetivo) e somos uma única associação com o CNPJ 44.593.429/0001-05. A efetivação do apoio apoio poder ser feito de duas formas:

- Apoio feito diretamente à associação, pelo CNPJ 44.593.429/0001-05;
- Compra das cotas pelo site do [apoia-se](https://apoia.se/devpr);

Para tratar os detalhes ou ter suas dúvidas respondidas, podemos agendar uma visita ou mesmo tratar através desse e-mail.

O DevParaná Conference 2024 é uma oportunidade única para investir no crescimento e atualização dos seus colaboradores junto à comunidade tecnológica regional. Ao apoiar nossa conferência, sua empresa contribuirá diretamente para o avanço da inovação e do conhecimento em nossa região, fortalecendo sua marca entre milhares de apaixonados por tecnologia.

Enviamos em anexo o nosso Mídia Kit com alguns números relevantes. Além disso, não deixe de conferir os palestrantes e atrações deste ano em [nosso site](https://devpr.org). Contamos muito com o seu apoio!

Ficamos à disposição para quaisquer dúvidas e esperamos poder contar com sua colaboração para tornar o DevParaná Conference 2024 um evento memorável e impactante.

Desde já, agradecemos sua atenção e apoio.

Atenciosamente,

[Seu Nome]

**Comment by ByIvo** [comment]
@guiseek Preciso do media kit da conf 2024; Caso tenha algo pendente, mandar o editável para eu preparar.

**Comment by ByIvo** [comment]
[midiakit.pdf](https://github.com/codaqui/institucional/files/15474975/midiakit.pdf)

**Comment by ByIvo** [comment]
Link do Figma:
https://www.figma.com/design/yxWKZcR1Sn6ZZW2m9sCWAM/Mediakit?node-id=136-1371&t=x8N8BIqqQtdOoX4X-0

**Comment by GHamerschimidt** [comment]
Começamos o contato, foi enviado o email a pessoa responsável  e um pré alinhamento foi realizado em conjunto com o Francisco Thiago

**Comment by ByIvo** [comment]
[Midiakit.pdf](https://github.com/user-attachments/files/15742568/Midiakit.pdf)

**Comment by endersonmenezes** [comment]
Sem resposta.
