### ISSUE TITLE
[Brindes] Chaveiros

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#219]
Custo do Chaveiro: 1,40R$
Considerando comida para o dia da montagem.

Custos atualizados:
1mm2 de acrílico cortado: R$ 450,00
1000 argolas: R$ 226,08
1000 Zip Locks:  R$ 46,61
1000 elo chaveiro: R$ 44,52

**Comment by ByIvo** [comment]
@guiseek Preciso do media kit da conf 2024; Caso tenha algo pendente, mandar o editável para eu preparar.

**Comment by ByIvo** [comment]
Pedido das argolas:
<img width="572" alt="image" src="https://github.com/codaqui/institucional/assets/5186894/93b55bb5-f61a-4ebd-8b8f-bc09671fa137">

**Comment by ByIvo** [comment]
Dados dos zip locks:
<img width="1173" alt="image" src="https://github.com/codaqui/institucional/assets/5186894/887e550a-2c59-47b7-898c-11c59c0ac5cb">
[Saco Zip Lock Saquinho Ziplock 5x7 C_ 1 000 Un Plastico.pdf](https://github.com/codaqui/institucional/files/15461416/Saco.Zip.Lock.Saquinho.Ziplock.5x7.C_.1.000.Un.Plastico.pdf)

**Comment by ByIvo** [comment]
Dados das peças de acrílico:
<img width="1146" alt="image" src="https://github.com/codaqui/institucional/assets/5186894/e8be8c78-913e-4218-802b-49eca3638824">

**Comment by ByIvo** [comment]
Ainda preciso comprar entre-elos

**Comment by endersonmenezes** [comment]
DevParaná - Montagem dos Brindes #1
Sábado, 8 de junho · 4:00 até 5:00pm

Pessoal, reservamos esse dia para montar os brindes, o horário oficial vai ser divulgado na próxima segunda (03/06). Reservem o dia.

**Comment by ByIvo** [comment]
@guiseek 767,21 é o total gasto; Não há acréscimos planejados.

**Comment by guiseek** [comment]
> [@guiseek](https://github.com/guiseek) 767,21 é o total gasto; Não há acréscimos planejados.

Reembolso feito ✅
