### ISSUE TITLE
[Financeiro] Almoço

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#221]
- Entrar em contato, falar do evento e verificar que tipos de alimentação (vegetariano, carne...)
- 40-50 pessoas.
- 800 pessoas.

**Comment by anadevti** [comment]
Nome do restaurante: Don Peponi

**Comment by anadevti** [comment]
Mandado mensagem no Instagram

**Comment by anadevti** [comment]
mandado mensagem no WhatsApp, aguardando resposta.

**Comment by anadevti** [comment]
conversando com a galera, eles não estão respondendo. estou pesquisando por outros estabelecimentos. aceito indicações!! 💯

**Comment by endersonmenezes** [comment]
Indicação -> La Gondolla

**Comment by endersonmenezes** [comment]
@GHamerschimidt vai verificar alguns restaurantes no local. 
@ByIvo vai verificar as restrições alimentares dos palestrantes.

**Comment by anadevti** [comment]
la gondolla não foi acessível para nós.

**Comment by anadevti** [comment]
enviado mensagem para o restaurante armazém!

**Comment by endersonmenezes** [comment]
Será que o setor de eventos do MC Donalds pode nos dar um preço bacana? E para Veganos/Vegetarianos o Vaka Louka ainda existe?

**Comment by anadevti** [comment]
vou mandar mensagem para o MC, o armázem não quis fechar parceria conosco :(

**Comment by anadevti** [comment]
enviado email ao MC. seguirei tentando contato com demais restaurantes da nossa região!

**Comment by anadevti** [comment]
MC nos retornou:

![Image](https://github.com/codaqui/institucional/assets/111382055/98e5c9b8-c988-432e-943d-6c39f26d93a3)

**Comment by endersonmenezes** [comment]
Foodtruck na rua.

**Comment by anadevti** [comment]
Enviado mensagem via Instagram para os foods que encontrei:

https://www.instagram.com/kingcheffmaringa/

https://www.instagram.com/tchekebabfoodtruck/

https://www.instagram.com/hanamarufoodtruck/

**Comment by endersonmenezes** [comment]
Enviado e-mail para SEMUC sobre ter foodtruck no estacionamento do local.

**Comment by anadevti** [comment]
Temos o primeiro parceiro de Food Truck confirmado!
- KingCheffMaringá ✅ https://www.instagram.com/kingcheffmaringa/ (Comentei com eles que haveria a possibilidade de postarmos sobre eles no nosso instagram alguns dias antes do evento)

**Comment by anadevti** [comment]
@endersonmenezes @elinatorresn Poderíamos postar algo sobre essa galera um dia antes do evento? aliás, eu vou confirmar com eles se está OK eles se instalarem na Rua, dado que fomos barrados de coloca-los na parte de dentro do Teatro.

**Comment by anadevti** [comment]
Mandado mensagem hoje para confirmar se está tudo ok.

**Comment by anadevti** [comment]
Vimos que com o foodtruck temos que lidar com muitas burocracias. Amanhã irei passar aos redores do teatro e tentar falar com restaurantes!
