### ISSUE TITLE
[Impressão 3D] Parceria com Colab de Impressão - 08/07/2024

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#229]
Primeiro contato com EVOA para apoio com impressão 3D.

**Comment by endersonmenezes** [comment]
Impressora do EVOA quebrada, porém possui uma empresa parceira. Está em confirmação se podemos usar.

**Comment by endersonmenezes** [comment]
Temos um outro contato pelo @ByIvo .

**Comment by endersonmenezes** [comment]
Verificar impressora da UniCesumar.

**Comment by endersonmenezes** [comment]
Verificar amigo do @guiseek.

**Comment by endersonmenezes** [comment]
Quantidade: 20 troféus.

**Comment by endersonmenezes** [comment]
Valor: 750R$.

**Comment by guiseek** [comment]
Aqui já fechou né @ByIvo ?

**Comment by anadevti** [comment]
Este card era referente aos trofeis @ByIvo ?

**Comment by ByIvo** [comment]
Conseguimos achar um parceiro muito bom pra isso; Vou colocar o contato dele na planilha de fornecedores
