### ISSUE TITLE
[TRILHA] HTML5

### ISSUE THREAD

**Issue by LuizFernando-TC** [codaqui/institucional#23]
A issue é um local de discussão, chame novas pessoas para ajudar a criar essa Trilha de Ensino. Utilize os campos abaixo como uma forma de se questionar e ajudar a iniciar uma discussão.

Discussed in https://github.com/codaqui/institucional/discussions/70

## Conteúdos Abordados na Nova Trilha de HTML5

1. Apresentação
2. Ambiente de desenvolvimento
3. Elementos básicos
5. Listas
6. Semântica e Hierarquia
7. Imagens, vídeos e aúdios
8. Links
9. Adaptação em várias telas
10. Tabela
11. Formulário
12. Formatação de texto
13. Título e legenda

Documentos (Guias):

- https://www.w3c.br/pub/Cursos/CursoHTML5/html5-web.pdf
- https://html.spec.whatwg.org/multipage/
- https://roadmap.sh/frontend
- https://www.w3schools.com/html/
- https://developer.mozilla.org/en-US/docs/Web/HTML
- https://www.w3.org/

### Profissionais

- Gustavo Guanabara (https://github.com/gustavoguanabara                   https://www.cursoemvideo.com/)       

### Bibliográficas

- https://devdocs.io/

**Comment by LuizFernando-TC** [comment]
1. Apresentação

**Comment by LuizFernando-TC** [comment]
2. Ambiente de desenvolvimento

**Comment by LuizFernando-TC** [comment]
3. Elementos básicos

Links:
- https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element

**Comment by LuizFernando-TC** [comment]
https://github.com/codaqui/institucional/discussions/70

**Comment by endersonmenezes** [comment]
@LuizFernando-TC to chamando um pessoal que entende de CSS para jogar aqui pra gente alguns conceitos que possam ser interessantes, influenciadores e etc. Vai ser interessante a gente pegar tudo que jogarem aqui e fazer uma curadoria e organização do conteúdo. Vamos aguardar um tempinho até o pessoal contribuir.

**Comment by LuizFernando-TC** [comment]
4. Listas
Links:
 - https://lrodrigo.sgs.lncc.br/wp/programacao/curso-de-html5-e-css3-5a-aula-listas/
 - https://www.devmedia.com.br/trabalhando-com-listas-ordenadas-no-html/21739
 - http://www.clem.ufba.br/tuts/html/c10.htm

**Comment by LuizFernando-TC** [comment]
> > 2. Ambiente de desenvolvimento
> 
> Acho que o ambiente de desenvolvimento poderia ser um paragrafo explicando que pelo fato de ser uma linguagem de marcação bem difundida, hoje você só precisa criar um arquivo `*.html`.... Vocêm acham que precisa de algo a mais?
> 
> @codaqui/conselho @codaqui/mentores @codaqui/membros ?

Acredito que é bom ter guias de instalação e configuração de softwares para trabalhar com o HTML5. O CSS3, por exemplo, pode ser o VSCode, figma e entre outros. No HTML5 pode ser o VSCode. O que acha?
