### ISSUE TITLE
[Institucional] Desenho de Badge para Holoping

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#230]
Nosso site parceiro: https://www.holopin.io/

Nossa badge do ano passado: 

![Image](https://github.com/codaqui/institucional/assets/11020807/3f5538c5-a4aa-4e0a-9915-efaa5d6862fe)

O que gostaríamos para esse ano:

- Uma badge da edição do evento. (Participação)
- Uma badge do DevParana (Com borda/estrela...) - https://docs.holopin.io/issuing-rewards/evolving-badges

Um extra:

- Seria utilizar o mesmo padrão para camisetas / adesivos que ainda não estão prontos, podemos criar uma nova task.

**Comment by jtheodsn** [comment]
Segue a proposta da badge com algumas opções de Cores para aprovarmos @endersonmenezes @ByIvo @guiseek 



![Image](https://github.com/codaqui/institucional/assets/172335139/2b43759c-12da-4b92-8235-230a9b7a025e)
![Image](https://github.com/codaqui/institucional/assets/172335139/479c8939-0341-4e9d-8abc-c03f648c1806)
![Image](https://github.com/codaqui/institucional/assets/172335139/aa7abce3-d566-4a0c-884f-f02240ee317b)
![Image](https://github.com/codaqui/institucional/assets/172335139/ff68920b-2ad2-4369-a0b5-fe7ca385103b)

**Comment by endersonmenezes** [comment]
Entra em contato com a https://www.nerdstickers.com.br/venda-corporativa/

**Comment by endersonmenezes** [comment]
Printi.com.br


![Image](https://github.com/codaqui/institucional/assets/11020807/668e2620-b94d-42f5-bf63-e7dd5e0eca25)

**Comment by endersonmenezes** [comment]
✅  Aprovado em reunião.

**Comment by anadevti** [comment]
podemos encerrar este card, turma?
