### ISSUE TITLE
[Institucional] Parcerias / Formalização de Meetups

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#231]
Parcerias:
- Parceria com Holopin
- Desconto em Bolsa de Estudo
- Jetbrains
- Figma (Codaqui)
- OpenAI
- GitHub Codaqui
- GitHub DevParana

Líder de Meetups:
- Acesso a $$ para CoffeBreak.
- Parceria para intermedio com locais.
- Marca
- Publicidade (Google Ads - Campanha Direcionada na Cidade Evento)

Hierarquia:
- [ ] Conselho
- [ ] Líderes de Grupos
- [ ] Membros
- [ ] Associados

Base de Locais (presenciais):
- [ ] base de dados de locais e contatos para eventos presenciais

Sistema de Cadastro de Eventos por Issue no GitHub:
- [ ] copiar ideia do Campus Expert?

Dois pontos de atenção:
- Meetup.com
- WhatsApp
- Instagram

**Comment by endersonmenezes** [comment]
Começando a testar com o Campos Valley e a @elinatorresn!

Liberado:
- https://opencollective.com/codaqui/projects/campos-valley
- https://www.figma.com/files/team/1030607159941021425/project/260487505/Campos-Valley?fuid=741723352695829536

**Comment by endersonmenezes** [comment]
@endersonmenezes -> Procurar o community manager do BR do GitHub.

**Comment by endersonmenezes** [comment]
https://hackclub.com/fiscal-sponsorship/

**Comment by adoniasvitorio** [comment]
Opa pessoal ! Versão inicial do documento de **Apoio Institucional**.
[Link Google Docs](https://docs.google.com/document/d/1ZHKVJemAVyI8a84M-AnFnt_JggaszwgecRmCT1Dd4DQ/edit?usp=sharing)

Documento esta aberto para edição/revisão.

**Comment by ByIvo** [comment]
@endersonmenezes essa tarefa está contigo? Precisa de algum apoio?
