### ISSUE TITLE
[Institucional] Sistema de Solicitação de Apoio para Evento (Financeiro/Palestras/Geral)

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#232]
https://github.com/campus-experts/being-an-expert

https://github.com/DeveloperParana/afiliados

https://github.com/DeveloperParana - README

**Comment by endersonmenezes** [comment]
DoD: Tentar usar o sistema de Issues para https://github.com/codaqui/institucional/issues/new/choose solicitação de brindes, apoio e quem sabe até para Newsletter.

**Comment by ByIvo** [comment]
Eu vou conversar com o GUi sobre o que foi testado e decidido.
Minha sugestão é usar uma ferramenta onde as pessoas contribuiam a partir do github; Assim a gente pode mapear as contribuições e identificar quem contribui sem necessidade de uma nova integração no common room.

**Comment by ByIvo** [comment]
Avaliar https://github.com/obsidianmd/obsidian-releases

**Comment by endersonmenezes** [comment]
Possívelmente transformar isso em uma iniciativa por que vai envolver mais que uma diretoria.

**Comment by renanceratto** [comment]
Na minha opinição o gasto de dinheiro deve ser centralizado ao máximo.

Se temos alguns 2 ou 3 membros da comunidade que estão encabeçando ações, estes 2 ou 3 poderiam ser os pontos focais de solicitação de recurso.

A hora que isso virar gargalo, vamos liberando mais pessoas como "autorizadores" e níveis de autorização pelo valor do reembolso

**Comment by endersonmenezes** [comment]
A associação vai gerir os gastos via https://opencollective.com/codaqui, as comunidades são livres se quiserem ter burocracia antes/depois.
