### ISSUE TITLE
[Empresa] EloTech

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#233]
Texto para copiar: https://github.com/codaqui/institucional/issues/215

Nome da Empresa: Elotech
Linkedin: https://www.linkedin.com/company/elotechgestao/
Quantidade de Cotas: 15

**Comment by ByIvo** [comment]
Email enviado na última quarta-feira, dia 29; Ainda aguardando resposta.

**Comment by endersonmenezes** [comment]
Avançou!
Declaração de Doação.
