### ISSUE TITLE
[Marketing] Divulgação em Redes Sociais

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#236]
- LinkedIn -> Profissional
- Instagram -> Misto
- Palestrantes
  - Video curto;
  - Divulgação cruzada.
  - ...

**Comment by elinatorresn** [comment]
**Planejamento de posts:**

**Semana 09/06 - 15/06**
- [ ] 📅 2024-06-11 | Apoie o devParaná Conference
- [ ] 📅 2024-06-13 | Conheça os primeiros palestrantes confirmados


**Semana 16/06 - 22/06**
- [ ] 📅 2024-06-17 | Palestrante confirmado 4
- [ ] 📅 2024-06-19 | Vídeo interativo (usando post-it) para divulgação da conf
- [ ] 📅 2024-06-21 | Benefícios: Por que participar e apoiar o devParaná Conference?


**Semana 23/06 - 29/06**
- [ ] 📅 2024-06-25 | Palestrante confirmado 5 
- [ ] 📅 2024-06-27 | Procura-se devs que queiram ------- 


**Semana 30/06 - 06/06**
- [ ] 📅 2024-07-01 | Palestrante confirmado 6 
- [ ] 📅 2024-07-03 | Depoimento de participantes 
- [ ] 📅 2024-07-05 | Vídeo palestrante chamando pessoal para o evento


**Semana 07/07 - 13/07**
- [ ] 📅 2024-07-09 | Palestrante confirmado 7  
- [ ] 📅 2024-07-09 | Tudo que estamos preparando para o evento 


**Semana 14/07 - 20/07**
- [ ] 📅 2024-07-14 | Inscrições gratuitas abertas
- [ ] 📅 2024-07-17 | Palestrante confirmado 8 
- [ ] 📅 2024-07-19 | Descritivo dos Workshops


**Semana 21/07 - 27/07**
- [ ] 📅 2024-07-22 | Preparado para o devParaná Conference? Confira nossas dicas para aproveitar ao máximo o evento 
- [ ] 📅 2024-07-24 | Cronograma completo do devParaná Conference 
- [ ] 📅 2024-07-26 | Último Lembrete para Inscrição 


**Dia do evento 28/07**
- [ ] 📅 2024-07-28 | É hoje 


_Obs: Esse planejamento não está escrito em pedras (kkk), podem ter alterações e inclusão de posts._

@ByIvo @endersonmenezes podem conferir?

**Comment by endersonmenezes** [comment]
Só os palestrantes confirmados eu acho que vai ficar apertado.
Sugestão do @guiseek foi divulgar mais o C4P e a votação pra ajudar a entrar em processo de convite.

**Comment by elinatorresn** [comment]
Belezaaa! Melhor começar então a divulgação de palestrantes quando a gente já tiver com eles definidos.
Ai encaixo mais o C4P e outros assuntos no lugar por enquanto

**Comment by endersonmenezes** [comment]
Dependência do Facebook/Instagram.

**Comment by endersonmenezes** [comment]
Ideia postagem sobre ONG.

**Comment by ByIvo** [comment]
Ideia: Divulgar a camiseta que vai ser distribuída para os apoiadores.
