### ISSUE TITLE
[Institucional] Parceria com Hotel - 01/07/2024

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#237]
- King Conform
- Ibis Budget -> Hus Hotel Maringá
- Caiuia

Alinhar com @ByIvo quantidade de chegadas na sexta/sábado/domingo.

**Comment by jgbz** [comment]
@endersonmenezes consegue dar assign da task? Ai fico no aguardo das informações do @ByIvo

**Comment by endersonmenezes** [comment]
Contato enviado no privado, Lucas.

**Comment by endersonmenezes** [comment]
Orçamento inicial para 10 pessoas.
Estamos organizando 4 caravanas oficiais, partindo de Ponta Grossa, Francisco Beltrão, Cascavel/Toledo, Foz de Iguaçu.

**Comment by endersonmenezes** [comment]
@jgbz entrando em contato com uma intermediadora de hotéis.
@GeovaneNorbert passou uma estimativa de pessoas de fora da cidade que devam vir pro evento.
