### ISSUE TITLE
[TRILHA] CSS3

### ISSUE THREAD

**Issue by LuizFernando-TC** [codaqui/institucional#24]
A issue é um local de discussão, chame novas pessoas para ajudar a criar essa Trilha de Ensino. Utilize os campos abaixo como uma forma de se questionar e ajudar a iniciar uma discussão.

Discussed in https://github.com/codaqui/institucional/discussions/71

## Conteúdos Abordados na Nova Trilha de CSS3

1. Apresentação
2. Ambiente de desenvolvimento
3. Animações e Transições
4. Fontes
5. Layout
6. Imagens
7. Listas
8. Seletores

Documentos (Guias):

- https://cssguidelin.es/
- https://www.w3schools.com/css/
- https://www.w3.org/
- https://developer.mozilla.org/en-US/docs/Web/CSS

### Profissionais

- Gustavo Guanabara (https://github.com/gustavoguanabara                   https://www.cursoemvideo.com/)        

### Bibliográficas

- https://devdocs.io/

**Comment by LuizFernando-TC** [comment]
Discussed: https://github.com/codaqui/institucional/discussions/71

**Comment by endersonmenezes** [comment]
@LuizFernando-TC to chamando um pessoal que entende de CSS para jogar aqui pra gente alguns conceitos que possam ser interessantes, influenciadores e etc. Vai ser interessante a gente pegar tudo que jogarem aqui e fazer uma curadoria e organização do conteúdo. Vamos aguardar um tempinho até o pessoal contribuir.

**Comment by ricardomaleixo** [comment]
Opa, 
eu Recomendo a documentação oficial do HTML, ela é bem complexa, mas vale pelo menos conhecer. 
https://html.spec.whatwg.org/multipage/

o RoadMap é um bom guia visual. 
https://roadmap.sh/frontend

Além da W3C. 
https://www.w3.org/
https://www.w3schools.com/html/
https://www.w3schools.com/css/

Também aqui. 
https://developer.mozilla.org/en-US/

**Comment by rioribeirods** [comment]
Acho importante ter um tópico só para seletores, notei recentemente que quem é fera no CSS sabe usar muito bem seletores. Inclusive é uma boa deixa para falar sobre do novo (e potente) :has() no CSS. Tem só 7 dias que a MDN colocou na documentação.

**Comment by endersonmenezes** [comment]
@LuizFernando-TC acho que já tem um material pra começar, bora abrir um PR?

**Comment by LuizFernando-TC** [comment]
> @LuizFernando-TC acho que já tem um material pra começar, bora abrir um PR? Quer que eu te ajude no modelo?

Sim, Enderson. Essa trilha ficará parecida com a de Javascript ou Python?

**Comment by endersonmenezes** [comment]
Eu acho que vai acabar sendo uma união, não precisa se limitar. Tem coisas boas que fizemos na de Python e tem coisas boas na de Javascript.

**Comment by endersonmenezes** [comment]
A base da trilha já está em nosso ambiende de desenvolvimento, qualquer colaboração é bem vinda.

**Comment by LuizFernando-TC** [comment]
1. Apresentação

Links:
-

**Comment by LuizFernando-TC** [comment]
2. Ambiente de desenvolvimento

Links

**Comment by LuizFernando-TC** [comment]
3. Animações

Links:

**Comment by LuizFernando-TC** [comment]
4. Fontes

Links:
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/OpenType_fonts_guide
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
