### ISSUE TITLE
[Orçamento] Brindes - 24/06/2024

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#246]
- Chaveiro
- Adesivo (2 modelos)
- 1 camiseta (Burnes) ou Caneca (Burnes)
- @ByIvo vai reunir com @GHamerschimidt e @anadevti para ver brindes para substituir o mousepad que era de má qualidade. 
- Ideias:
  - Bottons
  - Caderneta
  - Caneta
  - Cordão de Crachá
  - ...

**Comment by endersonmenezes** [comment]
Adeviso na Print em torno 20 centavos/unidade fazendo 1000.

**Comment by anadevti** [comment]
Gráfica do bairro que eu e Ana Lu fomos ver juntas

Tabela de preços: (Adesivos)

Adesivo vinil brilho / fosco / transparente 
4x4CM
UMA ARTE POR QUANTIA
200un. $ 55,00 (1 folhas)
400un. $ 90,00 (2 folhas)
600un. $ 130,00 (3 folhas)
800un. $ 160,00 (4 folhas)
1000un. $ 159,90 (5 folhas)promoção


Adesivo vinil brilho / fosco / transparente 
5x5CM
UMA ARTE POR QUANTIA
140un. $ 55,00 (1 folhas)
280un. $ 90,00 (2 folhas)
420un. $ 130,00 (3 folhas)
560un. $ 160,00 (4 folhas)
700un. $ 169,90 (5 folhas)promoção

------------------------------------------------------------------------------
Tabela de preços: (Panfletos)

PANFLETOS COUCHÊ 90G
IMPRESSÃO FRENTE
TAMANHO: 10X14 CM
1000   UN $ 199,99
2500   UN $ 249,99
5000   UN $ 360,00
10000 UN $ 640,00

PANFLETOS COUCHÊ 90G 
IMPRESSÃO FRENTE/VERSO
TAMANHO: 10X14 CM
1000   UN $ 249,99
2500   UN $ 269,99
5000   UN $ 440,00
10000 UN $ 780,00
-----------------------------------------------------------------------------------
Enviei no whats essas mesmas informações com mais opções, porém na minha opinião ficam mais caras.
