### ISSUE TITLE
[Marketing] Fotógrafo

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#251]
Orçamento inicial amigo do Gui - 1500R$ (sabado e domingo)
@anadevti ficou de ver com duas amigas.

**Comment by anadevti** [comment]
Mandei mensagem para a minha amiga Natalia, aguardando resposta dela.

**Comment by endersonmenezes** [comment]
@anadevti posta aqui o status da sua amiga, não precisa postar os valores.

**Comment by anadevti** [comment]
Ela topou nos ajudar @endersonmenezes só preciso passar pra ela melhor as informações de horários e etc. Sobre valores ficaria aquele que mandei no grupo mesmo.

**Comment by anadevti** [comment]
Conforme falamos em reuniões, iremos seguir com o outro profissional.
