### ISSUE TITLE
Post - Event Report - GitHub - 2024

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#270]
# Post Event Report [DEVPR CONF 2024] [2024/07/28]

## Attendance :dancers:

*Was it well attended? Was there a diverse attendance in terms of gender, socio-economic class, and race? Who was attending - students/professionals/a mix?* 

 - number of attendees in pre-events: ~100
 - number of attendees in first-day: ~80
 - number os attendees in second-day: ~650

## Venue :school:

The DevPR Conf 2024 was held at Teatro Calil Haddad, the largest theater in northern Paraná. Inaugurated in December 1996 and designed by architects Gilmar Ferdinandi and Maria Cristina Bittencourt, this venue is known for its outstanding infrastructure, making it one of the best theaters in Brazil. The theater, named after the pioneering Maringa playwright Calil Haddad, offers a main auditorium with a seating capacity of 759 people. The stage, built in an Italian format, features a total area of 112 square meters, with 12 meters in depth, a proscenium of 4.50 meters, and an orchestra pit of 32 square meters. [More information about the theater.](http://www3.maringa.pr.gov.br/cultura/?cod=teatro/1)

The venue was well-suited for the conference, accommodating the attendees comfortably across the two days. The theater's excellent acoustics and spacious seating contributed to a successful event atmosphere, allowing for clear presentations and engaged participation from all attendees.

## Planning vs Implementation :paperclip:

The event followed the initial plan with only minor adjustments. The schedule was followed, with a few sessions starting late, but overall the flow was smooth throughout the two days.

The energy and engagement of the attendees was high, considering the number of attendees, we were able to gather around 600 people but the space was designed to accommodate 759.

Regarding the giveaways, we had an ample supply of items that arrived on time, however, the event stickers and badge lanyards we ordered did not arrive on time due to a printer error. However, we had leftover kits, so next time we may consider adjusting the quantities based on attendee interest or offering different types of items that might appeal more to our audience.

On the budget side, we stayed within our planned expenses, even with some minor unexpected costs. There were a few areas where we could have saved more, such as reducing the number of printed materials, and the commitment to catering which was not as economical as expected; although the quality was excellent.

We had to purchase some extra cables and adaptors to support the event’s AV requirements, so that the equipment brought by the presenters would be easily accessible on the theatre stage.

In conclusion, the event was successful and adhered to plan, there are some lessons learned for future planning, particularly in terms of more accurately forecasting giveaway needs and managing catering orders to avoid waste.

## Positives :+1:

- Excellent venue with great acoustics and comfortable seating.
- Quality of speakers (some tech YouTubers) and the most proportional division possible between male and female speakers.
- High engagement from attendees throughout the event.
- Stayed within planned budget.
- Gift kits arrived on time. We were able to add stickers and GitHub items to all kits along with notebooks, bookmarks, badges, t-shirts or mugs, and they were well received.
- High quality buffet that was appreciated by the supporting participants, organization and speakers.
- Weekly meetings to organize the event.

## Negatives :-1:

- Slightly delayed schedule. For the next event, we should avoid adding “surprise” speeches and announcements that will gradually eat into the planned time.
- Event stickers and badge lanyards did not arrive on time due to a printing error.
- This year we ran a crowdfunding campaign instead of selling tickets, we are considering whether we will continue doing it this way.
- We no longer want to be responsible for lunch, even for just a few people.

**Comment by elinatorresn** [comment]
Fiz algumas atualizações @endersonmenezes

**Comment by endersonmenezes** [comment]
Boa! Vou tentar ver os outros pontos. Precisamos da foto para isso também @guiseek será que sai essa semana?

**Comment by ByIvo** [comment]
Renato, que fez o reels, pode ter vários conteúdos para ajudar com a parte de marketing.

**Comment by endersonmenezes** [comment]
Aberto um ticket para o time do GitHub.
