### ISSUE TITLE
1º Hackathon Online - Codaqui

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#281]
- [LandingPage](https://codaqui.github.io/hackathon/#inicio) | [ Repositório](https://github.com/codaqui/hackathon)
- Regulamento [PDF](https://drive.google.com/file/d/1vE_ugG4Vb6OQQXufqNDfacv5eW76DlDA/view?usp=sharing) | [Docs](https://docs.google.com/document/d/1vQ2wEaeblfjPHN-VRdeSouSrBGm20uoNhOCd6HgFlg4/edit?usp=drive_link)
- [Formulário de inscrição](https://forms.gle/F7gvZ25yet56ks5j8)

Pendências:
- [ ] Elaborar regulamento - 2 semanas.
   - [X] Equipes de 5 pessoas.   
  - Como será a avaliação? Banca? Projeto entregue, o que conta é o ultimo commit do dia X. Banca técnica tem 1 semana. Banca popular, postado foto instagram, a que tiver mais curtida no dia X. Encerramento aovivo.
   - [ ] Definir premiação
     - 500,00R$ - Codaqui 
       - 5 kits fisícos (popular + tecnico)
       - 5 kits fisicos (popular + tecnico a definir)
     - @endersonmenezes buscar mais patrocinadores.
     - @anadevti falar com AWS.
     - Escola de Ingles (Brindes)
     - Livros com Casa do Código
     - Livros com Inovatec
     - Livros da JBC
   - [ ] Definir regras para participação
     - [ ] Participante
       - [ ] 14-18 anos
     - [ ] Lideres de Equipe
       - [ ] 18-20 anos
     - [ ] Mentores de Equipe
       - [ ] (+2 anos de profissão)
- [ ] Fazer formulário de inscrição
- [ ] Publicar landing page
- [ ] Divulgar nas redes sociais
- [ ] Definir palestrantes
- [ ] Convidar monitores e definir agendas
- [X] Autorização - @gabsgeografo

**Comment by anadevti** [comment]
ideia de desafio: Soluções tecnológicas para combater o bullying nas escolas

**Comment by jtheodsn** [comment]
Pessoal, se precisarem de ajuda com relação a Identidade Visual do evento, como: (LPs de Cadastro e Sobre o Evento, Banners, Panfletos, e afins) fiquem a vontade para me chamar no whats para alinharmos, estou a disposição!

**Comment by anadevti** [comment]
Organização e detalhes [aqui](https://www.notion.so/thaifurforo/Hackathon-2024-11-fffc161f1bda8076bc02da9145bc3b2b)

**Comment by anadevti** [comment]
Aws tem interesse em nos patrocinar, mas precisamos enviar o sponsorship (tipo um Media Kit) para eles avaliarem, precisamos ter a proposta bem definida com os detalhes. Estou rascunhando [Neste Doc](https://docs.google.com/document/d/1FqF6LN-eTYIbxEz_-p4KPavJhlwhsHX7ryhyE6epVS4/edit) básico.

**Comment by anadevti** [comment]
Vamos utilizar o Forms para cadastro do pessoal? valeria a pena desenvolver uma landing page pra isso?

**Comment by endersonmenezes** [comment]
Data: 15/11/2024 (À confirmar com Stone, presencial.)

**Comment by endersonmenezes** [comment]
Falar com o Jurídico para termos e inscrição com os pais.

**Comment by endersonmenezes** [comment]
GItHub <> Stone (Tentativa)

**Comment by thaifurforo** [comment]
@anadevti vamos fazer uma landing page sim, o @marcosjmm85 vai ajudar nessa parte

**Comment by thaifurforo** [comment]
Media kit sendo elaborado para patrocínios: https://github.com/codaqui/institucional/issues/307

**Comment by thaifurforo** [comment]
[Documento enviado para Mavi](https://docs.google.com/document/d/1_O2AJqogXKuWDsDPRTSazbU35-rlcjkDyH3B8ArocLQ/edit?usp=sharing)

Falou que vai dar resposta esta semana ainda

**Comment by endersonmenezes** [comment]
Cogitar local da FIAP em Curitiba. (@anadevti )

**Comment by anadevti** [comment]
Mavi nos informou que iremos ter a Resposta no dia 20/09.

**Comment by gabsgeografo** [comment]
Se precisarem de gente para fazer conteúdo para mídias sociais (sobretudo Instagram), estou a disposição

**Comment by gabsgeografo** [comment]
> ideia de desafio: Soluções tecnológicas para combater o bullying nas escolas

Gosto da ideia!

**Comment by endersonmenezes** [comment]
Ideia da @anadevti: possível carro para sair de Maringá.

**Comment by thaifurforo** [comment]
[23/09] Mavi não deu retorno na sexta (20/09)
Hoje perguntei novamente e ela falou que iria ver ainda hoje, mas também ainda não retornou

Pra gente não ficar agarrado nisso, pensei em pensarmos em outros locais, e talvez até mesmo em pensar em fazer esse primeiro Hackathon em Maringá onde temos uma rede de apoio maior, se acharem que faz sentido para o público também (não conheço muito bem o perfil da cidade)
Assim podemos ganhar mais experiência em um ambiente mais controlado, para levar o know-how para os próximos

O que acham?

**Comment by endersonmenezes** [comment]
Ideia aprovada, vamos buscar parceiros em Maringá para realização, escolas para divulgação.

**Comment by anadevti** [comment]
Acho que seria uma boa ver a possibilidade de fazer no parque de exposições aqui de maringá, lá é um ambiente já conhecido por Hacka's, e é um bom ponto de referencia, e acredito que dependendo da sala que pegarmos lá, caberia no minimo umas 40 pessoas. Tenho o contato de um ex professor meu, o erinaldo ele iria amar a ideia, pois ele tem muitas frentes em relação ao curso tecnico para o pessoal aqui de maringá e sarandi, seria uma boa pessoa para pegarmos alguns insights!

**Comment by endersonmenezes** [comment]
@anadevti vê o lugar que você sugeriu, se não, vê da Kleber (SENAI) para fazer na AMTECH, tentamos contato pelo Rael.

**Comment by endersonmenezes** [comment]
@thaifurforo pode seguir tentando parceria pela Stone, se eles conseguiram ajudar com algo perfeito 👍🏽

**Comment by anadevti** [comment]
Media Kit enviado ao erinaldo, logo mais irei pedir um feedback dele sobre o material!

**Comment by thaifurforo** [comment]
- Kleber do SENAI irá verificar hoje à tarde em reunião sobre a disponibilidade da data para o local
- Enviei para ele também o Media Kit do evento
- Sobre a estrutura disponível do local, alguém de Maringá teria disponibilidade para ir na quarta-feira encontrar com ele e conhecer? Pontos importantes a verificar:
   - Computadores disponíveis para os participantes?
   - Pessoal para suporte tecnológico?

**Comment by endersonmenezes** [comment]
- Contato com a FCV.

**Comment by thaifurforo** [comment]
Resposta Kleber:
- Local: SENAI
- Labs: 1 para 30 pessoas e 4 para 16 pessoas
- Auditório: 50 pessoas

**Comment by endersonmenezes** [comment]
@thaifurforo ele estará disponível pro feriado? @anadevti o que acha do evento ser Online?

**Comment by anadevti** [comment]
@endersonmenezes Por ser nosso primeiro evento de Hacka eu acho uma boa, até pra termos uma noção de como será a aderência do pessoal, patrocinadores, palestrantes e tal. então eu super concordo fazermos de forma online.

**Comment by thaifurforo** [comment]
LandingPage -> https://www.canva.com/design/DAGPqdZG3wc/Qu1td1ymfaJaK1AUzqV9cA/edit?utm_content=DAGPqdZG3wc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
@marcosjmm85 irá fazer o código com base nesse design

**Comment by endersonmenezes** [comment]
21/09 - Grupo de Trabalho

```
Elaborar regulamento
Fazer formulário de inscrição
Publicar landing page
Divulgar nas redes sociais
Definir palestrantes
Convidar monitores e definir agendas
```

**Comment by endersonmenezes** [comment]
Adiamento da data, sem definição ainda.

**Comment by thaifurforo** [comment]
Ideias para premiação:

Vouchers para cursos online:
Alura e FIAP (ana poderia entrar em contato com o gustavo)
vouchers aws (ana pode fazer a ponte com a aws community)

Kits de desenvolvimento (Hardware)
Arduino, Raspberry PI

Livros de Tecnologia, ou Programação em si
Poderíamos tentar fazer parceria com a Casa do Código

(passando do do doc pra ca, ideias da @anadevti)

**Comment by thaifurforo** [comment]
LandingPage -> https://codaqui.github.io/hackathon/#inicio
Regulamento -> https://drive.google.com/file/d/1vE_ugG4Vb6OQQXufqNDfacv5eW76DlDA/view?usp=sharing
Formulário de inscrição -> https://forms.gle/F7gvZ25yet56ks5j8

**Comment by thaifurforo** [comment]
- LandingPage pronta (falta corrigir a programação)
- Formulário de inscrição WIP
- Regulamento pronto

**Comment by ByIvo** [comment]
Regulamento precisa de revisão, Landing page necessita pequenos ajustes e o formulário vai ser feito hoje durante a formação de salas mistas. Após isso, podemos lançar o evento a públíco.

**Comment by guiseek** [comment]
O munif pediu pra encaminhar aqui

Eu li o regulamento, lembrei de umas coisa da reunião que teve na UEM e perguntei também pro chatgpt, tem algumas coisa pra pensar:

-Tem algum termo de propriedade intelectual ? Vai ser obrigatoriamente livre, vai ser dos integrantes, etc...

-Achei o termo de uso de imagem e voz simples como tem menores, acho que precisa de algum profissional para ver.

-Vamos ter uma equipe de monitoramento ? Tipo alguém nas salas que o pessoal estiver utilizando para conversar, por serem menores?

-Será que compensa fazer um seguro de resposabilidade civíl ? Será que é caro ? 

-Parece que tem um tal de termo de "Participação online e exposição digital" para menores no Brasil.

**Comment by thaifurforo** [comment]
Fechando esta issue pois será substituída pela iniciativa e suas respectivas subtasks: #328
