### ISSUE TITLE
Divulgação de Fotos e Videos da DevPR Conf 2024

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#286]

**Comment by endersonmenezes** [comment]
Mensagem enviada para o fornecedor.

**Comment by guiseek** [comment]
A previsão que ele havia dado era de entregar no final de semana passado.
No entanto eu disse a ele que nós preferimos qualidade ao invés de tempo,
pra ele não fazer na correria mas fazer um baita video… Entendo que valerá
a pena aguardar algumas semanas, vamos aguentar a ansiedade, heheh. Fotos é
mais rápido a entrega mesmo, vídeo demanda edição e dá um trabalho bom
editar…

Em qui., 8 de ago. de 2024 às 15:25, Enderson Menezes (Mr. Enderson) <
***@***.***> escreveu:

**Comment by ByIvo** [comment]
O prestador está enrolado para entregar e enquanto isso, para não ficarmos dependentes dele, solicitei ao voluntário Renato para entregar as filmagens que ele fez durante a manhã.
