### ISSUE TITLE
Reunião com o SENAI

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#289]
Enviei uma mensagem solicitando modelo de datas e de reunião.

**Comment by ByIvo** [comment]
Solicitando contato com o @endersonmenezes

**Comment by endersonmenezes** [comment]
Agendado para terça-feira.

**Comment by ByIvo** [comment]
Amanhã a tarde (20/08), eu @ByIvo  e o @GHamerschimidt  vamos até o Senai para falar sobre as parcerias.

**Comment by GHamerschimidt** [comment]
Notas tomadas durante a visita:

Infraestrutura: 
- Auditório 80 pessoas (sem mesas), 5 (com mesas)

**Comment by ByIvo** [comment]
Contato adicionado na planilha de parceiros do DevPR
