### ISSUE TITLE
Arquitetura Terraform para Google Workspace

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#290]

**Comment by endersonmenezes** [comment]
https://github.com/codaqui/terraform-google-workspace

**Comment by anadevti** [comment]
Docs úteis:

https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs
https://developer.hashicorp.com/terraform/tutorials/it-saas/google-workspace
https://cloud.google.com/docs/terraform/best-practices-for-terraform?hl=pt-br

**Comment by anadevti** [comment]
Ainda não tive tempo de falar com o meu Líder sobre um possível overview sobre Terraform para nós, irei mandar mensagem para ele amanhã!

**Comment by endersonmenezes** [comment]
Inicio já funcional e com o state localmente https://github.com/codaqui/terraform-organization... Próximo passo é adicionar a SA no repositório e colocar esse state pra dentro :)

**Comment by endersonmenezes** [comment]
Lista de Atividades:
- [ ] Funcionalidade de Grupos
- [ ] Funcionidade de Drive (se possível)
- [ ] tfstate na Nuvem
- [ ] GitHub

**Comment by endersonmenezes** [comment]
Matando essa task, mas precisamos deixar isso como pendência no Backlog.
