### ISSUE TITLE
[Discussão] Gerador de Sites Estáticos

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#297]
Ferramentas:
- https://www.gatsbyjs.com/
- https://strapi.io/
- https://jekyllrb.com/

**Comment by adoniasvitorio** [comment]
> Ferramentas:
> 
> * https://www.gatsbyjs.com/
> * https://strapi.io/
> * https://jekyllrb.com/

Colaborando um pouco mais sobre as ferramentas.
 * https://strapi.io necessita de SGBD para persistir os dados. Suporte a PostgreSQL e MySQL ...ou SQLite.
 * https://www.gatsbyjs.com pode ser hospedado com netilify por exemplo. Na ultima vez que olhei fornecia um CMS.

**Comment by ByIvo** [comment]
https://gohugobrasil.netlify.app/

**Comment by ByIvo** [comment]
Eu vou conversar com o GUi sobre o que foi testado e decidido.
Minha sugestão é usar uma ferramenta onde as pessoas contribuiam a partir do github; Assim a gente pode mapear as contribuições e identificar quem contribui sem necessidade de uma nova integração no common room.

**Comment by ByIvo** [comment]
Avaliar https://github.com/obsidianmd/obsidian-releases
