### ISSUE TITLE
[TRILHA] Algoritmos

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#3]
A issue é um local de discussão, chame novas pessoas para ajudar a criar essa Trilha de Ensino. Utilize os campos abaixo como uma forma de se questionar e ajudar a iniciar uma discussão.

## Conteúdos Abordados na Nova Trilha de Algoritmos

1. Definição

### Profissionais
- 

### Bibliográficas

- https://www.amazon.com.br/C%C3%B3digo-limpo-Robert-C-Martin/dp/8576082675/
- https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/
- https://www.amazon.com.br/Cracking-Coding-Interview-Programming-Questions/dp/0984782850/
- https://novatec.com.br/livros/entendendo-algoritmos/
- https://the-algorithms.com/pt

**Comment by endersonmenezes** [comment]
Queria tentar abordar alguns casos comuns dentro de algoritmos o que acham?

**Comment by LuizFernando-TC** [comment]
Acho bom ter uma trilha de algoritmos
