### ISSUE TITLE
#1 AWS UG Maringá

### ISSUE THREAD

**Issue by anadevti** [codaqui/institucional#305]
Card criado para dar visibilidade nas questões do User Group AWS em maringá.

**Comment by anadevti** [comment]
Redes criadas até o momento:
Linkedin
Meetup

Em andamento:
Canal no Youtube
Instagram

**Comment by anadevti** [comment]
- Data do primeiro encontro: 28 de setembro, irá ser em um sábado

- Local: Unicesumar, duração 1h 30m? 1h? - alinhar com o coordenador

- Palestrantes: pessoa 1, pessoa 2, Temas?

- Abro call 4 papers? Convido pessoas específicas?

- Brindes? 

- CoffeBreak a aws paga - alinhar com a Nelly

**Comment by endersonmenezes** [comment]
@anadevti me pede o contato do Marcel.

**Comment by anadevti** [comment]
@ByIvo @endersonmenezes Pessoal, poderiam me apoiar com kits para os palestrantes por favor?

**Comment by anadevti** [comment]
Falando com o Ivo no whats

**Comment by endersonmenezes** [comment]
@anadevti @ByIvo deu tudo certo? Qual foi a proposta?

**Comment by anadevti** [comment]
Deu tudo certo pessoal! O pessoal amou, nós conseguimos trocar muitas figurinhas, realmente foi sensacional demais!! já estou organizando o segundo encontro. E no dia algumas pessoas vieram falar comigo que teriam interesse em me apoiar na organização de tudo, irei chama-las nos próximos dias!

**Comment by anadevti** [comment]
![Image](https://github.com/user-attachments/assets/584dc0cb-b21b-4b5a-b98e-cb119d4bdf3d)
![Image](https://github.com/user-attachments/assets/26885a81-f52d-4b22-94c7-fdf8222a2410)
![Image](https://github.com/user-attachments/assets/75eaef94-d8ad-4493-9c4c-72540b826857)
![Image](https://github.com/user-attachments/assets/67d1214c-434d-4bd6-ad5a-6538a6c14da4)
