### ISSUE TITLE
Media Kit da Associação

### ISSUE THREAD

**Issue by anadevti** [codaqui/institucional#307]
- [Estrutura sponsorship](https://docs.google.com/document/d/1FqF6LN-eTYIbxEz_-p4KPavJhlwhsHX7ryhyE6epVS4/edit?usp=sharing)
- [[WIP] MediaKit](https://www.canva.com/design/DAGP7bDPxxw/_sLOBmmD1pw0aNDVefXhgw/edit?utm_content=DAGP7bDPxxw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by endersonmenezes** [comment]
[Mediakit.pdf](https://github.com/user-attachments/files/17021090/Mediakit.pdf)

**Comment by endersonmenezes** [comment]
Revisei o que tinha! :p

**Comment by endersonmenezes** [comment]
@anadevti consegue bolar uma página de big numbers agora? Uma página só copilando informação das 3 comunidades (Campos Valley, DevPr e Codaqui), dando foco pro melhor de cada?

**Comment by anadevti** [comment]
@endersonmenezes ainda não consegui atualizar por conta de alguns contra-tempos que tive. amanhã irei atualizar!

**Comment by gabsgeografo** [comment]
Me coloco à disposição para ajudar com o media kit

**Comment by anadevti** [comment]
Adicionei informações sobre a campos valley, no "Sobre nós". @endersonmenezes @gabsgeografo e @elinatorresn poderiam validar se está ok?

**Comment by elinatorresn** [comment]
Pedi acesso @anadevti

**Comment by anadevti** [comment]
Estamos revisando o Media Kit! 

Pessoas que estão colaborando:
@thaifurforo @gabsgeografo @elinatorresn

**Comment by thaifurforo** [comment]
Thread no Discord: https://discord.com/channels/829882821559451659/829883017123463198/1290492004056174644

**Comment by anadevti** [comment]
Media Kit enviado ao erinaldo, logo mais irei pedir um feedback dele sobre o material!

**Comment by endersonmenezes** [comment]
Versão 1 ✅
