### ISSUE TITLE
[Comercial] Contato com Empresas e Empresário

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#309]
Antes de qualquer formatação de modelo comercial, vamos entrar em contato com as empresas para entender as dores e necessidades que eles tem as quais poderíamos trabalhar com a associação e projetos, assim podendo formatar um "produto" que tenha maior aceitação.

Inicialmente o que pensamos como pauta para as reuniões com as empresas é o que está descrito abaixo, caso tenham qualquer outro ponto para levantarmos também por favor nos indique.

### Pauta esperada a ser discutida:

**Treinamentos / Capacitações internas**

- Como são feitos os treinamentos dos desenvolvedores da sua empresa?
- Vocês tem algum programa de desenvolvimento profissional dentro da empresa?
- O budget para treinamentos na empresa é definido anualmente?

**Seleção**

- Como vocês buscam novos profissionais para sua empresa?
- Vocês tem algum programa de treinees para formar futuros profissionais para sua empresa?

**Comunidade**

- Qual a relação da sua empresa com a comunidade de desenvolvimento de software?
- Seus funcionários participam de alguma comunidade de desenvolvimento de software?

**Eventos**

- Sua empresa patrocina algum evento em algum evento?
- Sua empresa organiza algum tipo de evento?

**Tecnologias** 

- Quais as linguagens de programação que sua equipe de desenvolvimento utiliza?
- Quais os frameworks mais comuns que sua equipe de desenvolvimento utiliza?
- Quais as técnicas de desenvolvimento utilizadas pela sua equipe de desenvolvimento? Ex: kanban, scrum

**Comment by endersonmenezes** [comment]
@ByIvo já rolou café?!

**Comment by renanceratto** [comment]
Proximas ações com Patroni
- Reunião com SEBRAE
- Reunião com Cesar + João
