### ISSUE TITLE
Discussão sobre financiamento de eventos

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#310]
- Critério para apoio de eventos;
- Critério para apoio financeiro;

**Comment by endersonmenezes** [comment]
Ideia: Sistema de ponto mensal. Participação nas reuniões garante pontos.

**Comment by ferfabricio** [comment]
Dá para linkar essa task com uma requisição por parte dos eventos para serem incluídos no orçamento definido na #326

**Comment by endersonmenezes** [comment]
Duplicado: Definição de Politica Financeira.
