### ISSUE TITLE
#2 AWS UG Maringá

### ISSUE THREAD

**Issue by anadevti** [codaqui/institucional#314]
Card criado para dar visibilidade nas questões do User Group AWS em maringá.

**Comment by anadevti** [comment]
[Formulario para call 4papers](https://forms.gle/c2wwks79wCJLKsdWA)

## Segundo Evento
- Data: Confirmando...
- Local: Elotech (Capacidade máxima de 30 pessoas!)
- Palestrantes: bem provavelmente Teremos palestrantes da Elotech! 
- Duração: 1h 30m
- Brindes?
- CoffeBreak -> a aws paga, alinhar com a Nelly os demais!

**Comment by endersonmenezes** [comment]
O que precisa @anadevti ?!

**Comment by anadevti** [comment]
@endersonmenezes estou levantando algumas infos do lado da Elotech e AWS, inicialmente está tudo tranquilo!
