### ISSUE TITLE
[Institucional] Projeto com Instituto TIMBRE

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#322]
Objetivo: https://plan.org.br/fundo-acelere-o-relogio/

Quem eu sou?
Enderson Menezes, atualmente como Sênior SRE na Stone e ajudando a Codaqui com coisas burocráticas, projetos de DevOps e eventos.

Dois Projetos:
- Remoto
- Presencial
  - indígena (Luis)

----
Ideias:
- Conferência Remota 
- Presencial
  - Eventos Itinerantes pela Escolas Municipais
  - Eventos Itinerantes pelo Paraná (DevPR na Estrada Woman)

Pessoas:
- Gabriel
- Ana
- Thainara
- Josi (Grupo)

----
Responsável Associação: @endersonmenezes 
Proposta: **Diana e Lucia** cuidariam do desenho.

**Comment by endersonmenezes** [comment]
**TEMPLATE**

Quem eu sou?
Enderson Menezes, atualmente como Sênior SRE na Stone e ajudando a Codaqui com coisas burocráticas, projetos de DevOps e eventos.

**Comment by thaifurforo** [comment]
Quem eu sou?
Thainara Furforo, mas pode chamar de Thai. SWE Pleno no time de Crédito da Stone, tendo migrado para a carreira de tecnologia há dois anos, após quase dez anos de experiência na carreira administrativa. Formada em Administração com MBA em Marketing e Negócios pela UFJF e Especialização em Gestão de Projetos pela PUC-MG. Atualmente apoiando a Codaqui na organização de eventos e trilhas de ensino.

**Comment by anadevti** [comment]
Quem eu sou?

Ana Carolyne, mas pode chamar de aninha.

Atualmente SRE no time de Alertas e incidentes da Stone, trabalho na área faz 4 anos.

Quase formada em gestão de Tecnologia da Informação (este ano me formo graças a Deus kkkk) possuo ensino médio técnico em informática integrada, sempre fui apaixonada por tecnologia desde pequena, com 15 anos eu já sabia que queria seguir na área. Comecei me especializando em Redes e Cloud. Hoje sou líder de comunidade da AWS, e estou migrando para a área de Desenvolvimento no qual "fui pega de surpresa" quando comecei a mexer com automações na Stone e me apaixonei por códigos.

Atualmente estou apoiando a Codaqui na organização de eventos e trilhas de ensino!

**Comment by endersonmenezes** [comment]
@Divcarvalho depois coloca o link do Brainstorm aqui para a gente compartilhar com o pessoal na reunião.

**Comment by endersonmenezes** [comment]
----- Próxima encontro.
- Buscar instituições.
- Pensar em público-alvo. (Quantidade, local...)
- Envolvimentos dos voluntários.

PSC @Divcarvalho
