### ISSUE TITLE
[TRILHA] Analise de Dados

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#4]
A issue é um local de discussão, chame novas pessoas para ajudar a criar essa Trilha de Ensino. Utilize os campos abaixo como uma forma de se questionar e ajudar a iniciar uma discussão.

### Profissionais
- https://www.linkedin.com/in/teocalvo/
- https://www.linkedin.com/in/henriqueajnb/
- https://www.linkedin.com/in/gustavo-ferrari-3a9289/

### Bibliográficas

- https://www.kaggle.com/code/joaoavf/introducao-a-analise-de-dados-python-e-pandas/notebook

**Comment by endersonmenezes** [comment]
O que poderia ser uma boa trilha para ensinar jovens e adolescentes a aprender analisar dados e se questionar, de preferência com Python?

**Comment by guilhermenstorti** [comment]
@endersonmenezes seria interessante nessa trilha abordar temas de estrutura como construção de estrutura de banco de dados, data lake ou data warehouse? Como fundamentos pra que o aluno entenda a estrutura de onde os dados estão sendo consumidos.

**Comment by endersonmenezes** [comment]
Podem ser tópicos muito interessantes, preciso chamar alguém para contribuir aqui, estou distante da área.
