### ISSUE TITLE
Projeto 17 - Certificado Python

### ISSUE THREAD

**Issue by LuizFernando-TC** [codaqui/institucional#55]
### Discussed in https://github.com/codaqui/institucional/discussions/54

<div type='discussions-op-text'>

<sup>Originally posted by **LuizFernando-TC** October  5, 2022</sup>
Sugestão para o projeto 17 do certificado de Python:
1. Seu programa deverá exibir o dia da semana que foi 07/09/2022
2. Seu programa deverá exibir a difereça de dias entre 11/11/1918 e 01/09/1939</div>

**Comment by endersonmenezes** [comment]
Parabéns @LuizFernando-TC adicionei alguns comentários lá na discussão. Aqui reservaremos o espaço para assuntos técnicos. =] Estou acompanhando!
