### ISSUE TITLE
[TRILHA] Javascript

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#6]
## Palavras-Chaves (Resumo das Discussões)

- [x] 1. Apresentação
- [x]   - História de Origem da Linguagem
- [x]   - Ambiente de Desenvolvimento
- [x] 2. Introdução a Linguagem
- [x] 3. Variavéis de Tipos de Dados
- [X]   - Estrutura de Dados e Algoritmos
- [X] 4. Estruturas Lógicas e Condicionais | Estruturas de Repetição
- [X] 5. Expressões e Operadores
- [X] 6. Orientação e Objetos
- [X] 7. Interface e Herança
- [X] 8. Funções Async
- [X] 9. Conhecendo o Browser
- [X] 10. Abordagem Funcional
- [X] 11. TypeScript
- [X] 12. Manipulação de DOM
- [X] 13. Revisão de HTML5 e CSS3
- [x] 14. ECMAScript
- [x] - Diferença entre ES5 e ES6
- [X] 15. Internet
- [X]   - O que é uma API?
- [X]   - Construindo uma API
- [x] 16. Módulos em Javascript
- [x] 17. Frameworks
- [x]  - NodeJS
- [x]  - ExpressJS
- [x] 18. Debugando e Tratando Erros
- [x] 19. Leitura e Escrita de Arquivos
- [x] 20. Indicação de Livros
- [X] 21. Extra (Build a Video Game with Kaboom!)
- [X] https://www.youtube.com/watch?v=gOecj6Zktik

### Profissionais

- Rodrigo Branas
- https://www.youtube.com/c/ErickWendelTreinamentos
- https://www.youtube.com/c/NodeStudioTreinamentos

### Bibliográficas

- [Curso da Alura](https://www.alura.com.br/cursos-online-front-end/javascript)
- [Build a VideoGame with Kaboom by Replit](https://replit.com/curriculum/Build-a-Video-Game-with-Kaboom)
- [Javascript by Freecodecamp](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)
- [Javascript by CodeAcademy](https://www.codecademy.com/learn/introduction-to-javascript)
- [Roadmap](https://roadmap.sh/)
- [Javascript Completo 2018](https://www.udemy.com/course/javascript-completo-2018-do-iniciante-ao-mestre/)
- [DevDocs](https://devdocs.io/) - Indicação @LuizFernando-TC 
- [Fundação Bradesco - Javascript] - https://www.ev.org.br/cursos/introducao-ao-javascript

**Comment by endersonmenezes** [comment]
Pessoal, alguma ideia de onde começar?

**Comment by endersonmenezes** [comment]
https://replit.com/curriculum/Build-a-Video-Game-with-Kaboom

**Comment by LuizFernando-TC** [comment]
Não seria mais interessante criar uma trilha de HTML5 e CSS3 separada da trilha de Javascript?

**Comment by endersonmenezes** [comment]
`1. Apresentação`

`Ordem Indicada`: 1
`Avaliação da Ordem`: Acredito que está legal a gente começar estudando uma linguagem pela sua história e origem.

`Materiais de Referência`:
- https://www.cpt.com.br/cursos-informatica-desenvolvimentodesoftwares/artigos/linguagem-de-programacao-javascript-um-breve-historico
- http://shipit.resultadosdigitais.com.br/blog/javascript-1-uma-breve-historia-da-linguagem/
- https://developer.mozilla.org/pt-BR/docs/Glossary/JavaScript

`Video`:
- O que é JAVASCRIPT e para que serve, história e origem da linguagem - https://www.youtube.com/watch?v=pWseQJRL_2k

**Comment by LuizFernando-TC** [comment]
https://devdocs.io/

**Comment by endersonmenezes** [comment]
`2. Ambiente de Desenvolvimento`

`Ordem Indicada`: 2
`Avaliação da Ordem`: Acho que a ordem está bacana, porém diferente do primeiro pode ser que dê pra mudar, depende do que vamos fazer a frente.

`Materiais de Referência`:

- 


`Video`:
-

**Comment by LuizFernando-TC** [comment]
3. Variáveis de Tipos de Dados
links: 
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Grammar_and_types
https://www.todoespacoonline.com/w/2014/04/variaveis-em-javascript/
https://ricardo-reis.medium.com/tipos-de-dados-javascript-a1f6f498a7d4
https://www.w3bai.com/pt/js/js_datatypes.html#gsc.tab=0
https://www.devmedia.com.br/javascript-variaveis-e-constantes/41012

**Comment by LuizFernando-TC** [comment]
5. Estruturas Lógicas e Condicionais
Links:
https://www.treinaweb.com.br/blog/estruturas-condicionais-e-estruturas-de-repeticao-em-javascript
https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/Building_blocks/conditionals
https://www.todoespacoonline.com/w/2014/04/estruturas-condicionais-javascript/
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Expressions_and_operators

**Comment by LuizFernando-TC** [comment]
Talvez alguns links fique bom em outros tópicos

**Comment by LuizFernando-TC** [comment]
Livros sobre JavaScript:
Lógica de Programação e Algoritmos com JavaScript: uma Introdução à Programação de Computadores com Exemplos e Exercícios Para Iniciantes: https://www.amazon.com.br/L%C3%B3gica-Programa%C3%A7%C3%A3o-Algoritmos-com-JavaScript/dp/6586057906/ref=asc_df_6586057906/?tag=googleshopp00-20&linkCode=df0&hvadid=581934698281&hvpos=&hvnetw=g&hvrand=18077417048925109668&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9102204&hvtargid=pla-1646193652318&psc=1
Estruturas de Dados e Algoritmos com JavaScript: Escreva um Código JavaScript Complexo e Eficaz Usando a Mais Recente ECMAScript: https://www.amazon.com.br/Estruturas-Dados-Algoritmos-Com-Javascript/dp/8575226932/ref=asc_df_8575226932/?tag=googleshopp00-20&linkCode=df0&hvadid=379765802639&hvpos=&hvnetw=g&hvrand=18077417048925109668&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9102204&hvtargid=pla-811121404201&psc=1

**Comment by LuizFernando-TC** [comment]
7. Orientação e Objetos
Links:
https://www.freecodecamp.org/portuguese/news/programacao-orientada-a-objetos-em-javascript-explicada-com-exemplos/
https://www.devmedia.com.br/poo-trabalhando-com-classes-e-objetos-em-javascript/28434
https://www.alura.com.br/conteudo/javascritpt-orientacao-objetos
https://blog.matheuscastiglioni.com.br/orientacao-a-objetos-com-javascript/

**Comment by endersonmenezes** [comment]
`7. Interface e Herança`

`Materiais de Referência`:

- 

`Video`:
-

**Comment by endersonmenezes** [comment]
Para pesquisar:

- Conceito da linguagem script - 

@Kamisinha

**Comment by endersonmenezes** [comment]
Para pesquisar:
- Vantagens e desvantagens da linguagem script
- Estrutura básica da linguagem JavaScript
- Relação entre objetos e métodos JavaScript
- Adição de Comentários

**Comment by endersonmenezes** [comment]
`Funções Async`

`Materiais de Referência`:

- 

`Video`:
-

**Comment by endersonmenezes** [comment]
`Conhecendo o Browser e Manipulando o DOM`

`Materiais de Referência`:

- 

`Video`:

-

**Comment by endersonmenezes** [comment]
`Basico de HTML e CSS`

`Materiais de Referência`:

- 

`Video`:

-

**Comment by endersonmenezes** [comment]
`Internet e API`

`Materiais de Referência`:

- 

`Video`:

-

**Comment by endersonmenezes** [comment]
`ECMAScript 5 e 6`

`Materiais de Referência`:

- 

`Video`:

-

**Comment by endersonmenezes** [comment]
`Typescript`

`Materiais de Referência`:

- 

`Video`:

-

**Comment by LuizFernando-TC** [comment]
`Debugando e Tratando Erros`

`Materiais de Referência`:

- https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Control_flow_and_error_handling
- http://devfuria.com.br/javascript/debugando/
- https://github.com/braziljs/eloquente-javascript/blob/master/chapters/08-erros-e-manipulacao-de-erros.md

`Video`:

-

**Comment by LuizFernando-TC** [comment]
`Leitura e Escrita de Arquivos`

`Materiais de Referência`:

- https://pt.stackoverflow.com/questions/7974/escrevendo-e-lendo-arquivo-via-javascript
- https://www.botecodigital.dev.br/javascript/lendo-o-conteudo-de-um-arquivo-via-javascript/
- https://tableless.com.br/file-api-trabalhando-com-arquivos-locais-usando-javascript/

`Video`:

-

**Comment by LuizFernando-TC** [comment]
`Módulos em Javascript`

`Materiais de Referência`:

- https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Modules
- https://www.devmedia.com.br/trabalhando-com-modulos-no-javascript/40091
- https://blog.matheuscastiglioni.com.br/utilizando-modulos-javascript-de-forma-nativa/
- https://gabrieluizramos.com.br/modulos-em-javascript

`Video`:

-

**Comment by endersonmenezes** [comment]
`NodeJS e ExpressJS e Deno`

`Materiais de Referência`:
- https://nodejs.org/en/
- https://nodejs.org/en/about/
- https://deno.land/
- https://expressjs.com/pt-br/starter/installing.html

`Video`:

- https://www.youtube.com/watch?v=SDEwUZ7xuG0
- https://www.youtube.com/watch?v=asEzNp_Y-O8
- https://www.youtube.com/watch?v=pohvlFd0byI

**Comment by SOPHI-A9** [comment]
As vantagens de usar as linguagens scripts são variadas e podem ser usadas de maneiras diferentes: fácil de aprender e usar, código aberto e gratuito, portátil e multiplataforma, Permite uso em qualquer sistema operacional, Melhor desempenho no desenvolvimento de aplicações, e etc. 

A linguagem JS pode ser usadas de diversas maneiras, seu básico seria que nela podemos criar jogos e sites de diversas formas diferentes e do jeito que queremos. Nela podemos usar códigos da maneira certa para criarmos nossos jogos e sites, mas apenas um erro pode acabar com o código.

A relação entre métodos e objetos no JS é que qualquer tipo de dado pode ser um objeto, é quando uma propriedade armazena um valor se passa a ser chamado de método. Propriedades são valores e cada objeto é um valor, fazendo os dois se relacionarem.

https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/JavaScript_basics
https://kenzie.com.br/blog/script/
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Functions/Method_definitions
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Working_with_Objects

**Comment by ArtumosGOC** [comment]
`Relação entre objetos e métodos JavaScript`

`Materiais de Referência:`

- https://www.luis.blog.br/orientacao-a-objetos-classe-e-objeto-propriedades-e-metodos.html
- https://www.digitalocean.com/community/tutorials/how-to-use-object-methods-in-javascript-pt
- https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Working_with_Objects
- https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/Objects/Basics

`Vídeo Complementar:`

- https://www.youtube.com/watch?v=6d4mrARIIDg
- https://www.youtube.com/watch?v=n5uiJr-v0KQ

Responsável: @ArtumosGOC

**Comment by LuizFernando-TC** [comment]
O que acham de adicionar um tópico sobre data e hora?

**Comment by endersonmenezes** [comment]
@LuizFernando-TC leva discussão pro discussions, eu acho legal, vamos ver aonde tem sites interessantes sobre isso.
