### ISSUE TITLE
[TRILHA EXISTENTE] Python - Manipulando Arquivos - Trabalhando com SO - Fontes Externas

### ISSUE THREAD

**Issue by endersonmenezes** [codaqui/institucional#74]
### Discussed in https://github.com/codaqui/institucional/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **phsmith** October 15, 2022</sup>
O que acham de adicionarmos os seguintes tópicos na trilha de python:

- Interagindo com o sistema operacional
- Manipulando arquivos
- Consumindo dados de fontes externas</div>

**Comment by endersonmenezes** [comment]
Gente (@LuizFernando-TC  e @ArtumosGOC ) o @phsmith vai estar ajudando a gente a melhorar essa etapa, tem um pouco a ver com a postagem do blog que vocês vão fazer com a @thaifurforo . Em que local da Trilha vocês acham que ele pode adicionar isso, ou criar um novo tópico?

**Comment by phsmith** [comment]
@endersonmenezes não consigo efetuar o assign, talvez por não ser membro.

**Comment by endersonmenezes** [comment]
Precisava comentar aqui pra eu consegui kkk =]
Desculpa ai, estamos melhorando isso o/

**Comment by phsmith** [comment]
> Precisava comentar aqui pra eu consegui kkk =] Desculpa ai, estamos melhorando isso o/
Rsrs... Sossegado meu camarada!

**Comment by endersonmenezes** [comment]
Quando quiser, pode enviar o material aqui, ou pode fazer por PR também para `develop` que durante o encontro eu discuto com eles daí, o material que tiver estaremos discutindo na próxima sexta feira.
